defaults:
  - default.yaml

gpus: 1
accelerator: gpu
strategy: ddp
num_nodes: 1
replace_sampler_ddp: True
devices: auto
sync_batchnorm: True
auto_scale_batch_size: False

#plugins:
#  - _target_: pytorch_lightning.plugins.DDPPlugin
#    find_unused_parameters: True

# milli transformer batch_size=48, gpus=1