
_target_: tali.models.auto_builder.transformers.AutoVideoTransformers
config:
  transformer_num_filters: 128
  transformer_num_layers: 12
  transformer_num_heads: 8
  transformer_dim_feedforward: 512
  embedding_output_features: 512
