
_target_: tali.models.auto_builder.transformers.AutoVideoTransformers
config:
  transformer_num_filters: 256
  transformer_num_layers: 12
  transformer_num_heads: 8
  transformer_dim_feedforward: 1024
  embedding_output_features: 512
