_target_: tali.models.auto_builder.transformers.AutoCLIPVisionTransformer
config:
  grid_patch_size: 16
  embedding_output_features: 512
  image_resolution:
    - ${datamodule.config.image_shape.width}
    - ${datamodule.config.image_shape.height}
  transformer_num_filters: 768
  transformer_num_layers: 12
  transformer_num_heads: 12
  transformer_dim_feedforward: 3072