_target_: gate.models.resnet.AudioImageResNet
model_name_to_download: resnet50
pretrained: True
audio_kernel_size: 3
input_modality_shape_config:
  image:
    shape:
      channels: 3
      width: 224
      height: 224
    dtype: float32
  audio:
    shape:
      channels: 2
      width: 44100
    dtype: float32
