defaults:
  - optimizer_config: adam.yaml
  - lr_scheduler_config: cosine_annealing.yaml

_target_: tali.models.systems.DumbusPrime

embedding_output_features: 512
logit_scale: 1.0

image_embedding_config:
    _target_: tali.models.auto_builder.transformers.AutoDumbNet
    embedding_output_features: 512

audio_embedding_config:
    _target_: tali.models.auto_builder.transformers.AutoDumbNet
    embedding_output_features: 512

text_embedding_config:
    _target_: tali.models.auto_builder.transformers.AutoDumbNet
    embedding_output_features: 512

video_embedding_config:
    _target_: tali.models.auto_builder.transformers.AutoDumbNet
    embedding_output_features: 512

name: base_dumbnet