defaults:
  - default.yaml

upload_code_as_artifact:
  _target_: gate.base.callbacks.wandb_callbacks.UploadCodeAsArtifact
  code_dir: ${code_dir}

upload_ckpts_as_artifact:
  _target_: gate.base.callbacks.wandb_callbacks.UploadCheckpointsAsArtifact
  ckpt_dir: ${current_experiment_dir}/checkpoints/
  upload_best_only: False

log_multi_modal_similarity_prediction_heatmap:
  _target_: gate.base.callbacks.wandb_callbacks.LogMultiModalPredictionHeatmaps
  num_samples: 8

log_grads:
  _target_: gate.base.callbacks.wandb_callbacks.LogGrads
  refresh_rate: 100

log_configs:
  _target_: gate.base.callbacks.wandb_callbacks.LogConfigInformation
  config: null
