_target_: gate.datasets.hub.DataModule
dataset_config:
  dataset_root: ${data_dir}
  dataset_name: datamodule
  modality_config:
    image: True
    audio: False
    video: False
    text: False
  image_shape:
    channels: 3
    width: 288
    height: 176
data_loader_config:
  seed: ${seed}
  batch_size: ${batch_size}
  persistent_workers: True
  pin_memory: True
  prefetch_factor: 2
  num_workers: 2
  shuffle_train: True
  shuffle_eval: False
  use_dummy_dataloader: False
