_target_: tali.datasets.hub.TALIDataModule
config:
  dataset_root: ${data_dir}
  dataset_size_identifier: base
  dataset_name: ${datamodule.config.dataset_size_identifier}-tali
  modality_config:
    image: True
    audio: True
    video: True
    text: True
    name: v.${datamodule.config.modality_config.video}-a.${datamodule.config.modality_config.audio}-t.${datamodule.config.modality_config.text}-i.${datamodule.config.modality_config.image}
  rescan_paths: False
  num_video_frames_per_datapoint: 10
  num_audio_frames_per_datapoint: 220500
  num_audio_sample_rate: 44100
  image_shape:
    channels: 3
    width: 288
    height: 176
  text_context_length: 77
batch_size: ${batch_size}
persistent_workers: True
pin_memory: True
prefetch_factor: 2
num_workers: 2
shuffle_train: True
shuffle_eval: False
train_start_index: 0
val_start_index: 0
test_start_index: 0
train_num_samples: 90000000
use_dummy_dataloader: False
