
_target_: tali.models.auto_builder.transformers.AutoConv1DTransformers
config:
  embedding_output_features: 512
  resnet_num_filters: 8
  resnet_num_stages: 5
  resnet_num_blocks: 1
  resnet_adaptive_pool_output_features: 512
  resnet_dilated: false
  grid_patch_size: 32
  transformer_num_filters: 128
  transformer_num_layers: 12
  transformer_num_heads: 8
  transformer_dim_feedforward: 512